name: flutter_template
description: "flutter_template"
publish_to: 'none' 

version: 0.0.2

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.2'

# isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.0.3
  device_info_plus: ^8.2.2
  json_annotation: ^4.9.0
  talker_flutter: ^4.4.0
  flutter_smart_dialog: ^4.9.7+9
  stack_trace: ^1.11.1
  dio: ^5.5.0+1
  connectivity_plus: ^6.0.4
  http: ^1.2.2
  flutter_screenutil: ^5.9.3
  package_info_plus: ^8.0.1
  tdesign_flutter: ^0.1.6
  font_awesome_flutter: ^10.7.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0 # contains Isar Core
  path: ^1.8.3
  path_provider: ^2.1.0
  cached_network_image: ^3.3.1
  fvp: ^0.23.0
  video_player: ^2.9.1
  extended_image: ^8.2.1
  talker_dio_logger: ^4.4.1
  event_bus: ^2.0.0
  flex_color_scheme: ^7.3.1
  modal_bottom_sheet: ^3.0.0
  flutter_phoenix: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.2

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21