name: flutter_template_melos
version: 1.0.0

environment:
  sdk: ^3.9.0

dev_dependencies:
  melos: ^7.1.0

workspace:
  - apps/flutter_template
  - packages/core
  - packages/http_server
  - packages/updater
