name: flutter_template
description: "flutter_template"
publish_to: 'none' 

version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.0.3
  device_info_plus: ^8.2.2
  json_annotation: ^4.9.0
  talker_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

 