name: flutter_template
description: "flutter_template"
publish_to: 'none' 

version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.0.3
  device_info_plus: ^8.2.2
  json_annotation: ^4.9.0
  talker_flutter: ^4.4.0
  flutter_smart_dialog: ^4.9.7+9
  stack_trace: ^1.11.1
  dio: ^5.5.0+1
  connectivity_plus: ^6.0.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

 