name: flutter_template
description: "flutter_template"
version: 1.0.0+1

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.4"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  core: any
  updater: any
  get: ^4.7.2
  path_provider: ^2.1.5
  flex_color_scheme: ^8.1.1
  realm: ^20.1.1
  path: ^1.9.0
  csv: ^6.0.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1

dependency_overrides:
  core:
    path: ./packages/core
  updater:
    path: ./packages/updater


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/locales/

