name: flutter_template
version: 0.0.2
description: flutter_template
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: 3.22.2

dependencies:
  adaptive_dialog: ^2.1.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.4
  crypto: ^3.0.5
  cupertino_icons: ^1.0.6
  device_info_plus: ^8.2.2
  dio: ^5.5.0+1
  elegant_notification: ^2.2.2
  event_bus: ^2.0.0
  extended_image: ^8.2.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.9.3
  flutter_smart_dialog: ^4.9.7+9
  flutter_staggered_grid_view: ^0.7.0
  flutter_tts: ^4.0.2
  flutter_volume_controller: ^1.3.2
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.0.0
  fvp: ^0.23.0
  get: ^4.6.6
  get_storage: ^2.0.3
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  intl: any
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  jiffy: ^6.3.1
  json_annotation: ^4.9.0
  modal_bottom_sheet: ^3.0.0
  package_info_plus: ^8.0.1
  path: ^1.8.3
  path_provider: ^2.1.0
  photo_view: ^0.15.0
  pluto_grid: ^8.0.0
  pubspec_yaml: ^3.1.0
  regexpattern: ^2.6.0
  stack_trace: ^1.11.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  tdesign_flutter: ^0.1.6
  video_player: ^2.9.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0
  json_serializable: ^6.8.0
  package_rename: ^1.7.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: launcher_icon
  ios: false
  image_path: assets/icon/icon.png
  min_sdk_android: 21

package_rename_config:
  android:
    app_name: Flutter Template
    package_name: com.foliage.flutter_template
    override_old_package: com.foliage.flutter_template
    lang: kotlin
  windows:
    app_name: Flutter Template
    organization: foliage
    copyright_notice: Copyright ©️ 2022 foliage. All rights reserved.
    exe_name: flutter_template
