name: fs_widgets
version: 1.0.0+1
description: A new Flutter module project.

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  extended_image: ^8.2.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_smart_dialog: ^4.9.8+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_volume_controller: ^1.3.2
  get: ^4.6.6
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  pubspec_yaml: ^3.1.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.foliage.fs_widgets
    iosBundleIdentifier: com.foliage.fsWidgets
