import 'package:flutter/material.dart';

class ColorSchemes {
  ColorSchemes._();

  static const lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFF2B5DA8),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFD7E3FF),
    onPrimaryContainer: Color(0xFF001B3F),
    secondary: Color(0xFF305BAE),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFD9E2FF),
    onSecondaryContainer: Color(0xFF001944),
    tertiary: Color(0xFF405AA9),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFDBE1FF),
    onTertiaryContainer: Color(0xFF00174D),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    background: Color(0xFFFDFBFF),
    onBackground: Color(0xFF001B3D),
    surface: Color(0xFFFDFBFF),
    onSurface: Color(0xFF001B3D),
    surfaceVariant: Color(0xFFE0E2EC),
    onSurfaceVariant: Color(0xFF44474E),
    outline: Color(0xFF74777F),
    onInverseSurface: Color(0xFFECF0FF),
    inverseSurface: Color(0xFF003062),
    inversePrimary: Color(0xFFABC7FF),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF2B5DA8),
    outlineVariant: Color(0xFFC4C6D0),
    scrim: Color(0xFF000000),
  );

  static const darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFABC7FF),
    onPrimary: Color(0xFF002F65),
    primaryContainer: Color(0xFF00458F),
    onPrimaryContainer: Color(0xFFD7E3FF),
    secondary: Color(0xFFAFC6FF),
    onSecondary: Color(0xFF002D6D),
    secondaryContainer: Color(0xFF0D4395),
    onSecondaryContainer: Color(0xFFD9E2FF),
    tertiary: Color(0xFFB5C4FF),
    onTertiary: Color(0xFF032978),
    tertiaryContainer: Color(0xFF254290),
    onTertiaryContainer: Color(0xFFDBE1FF),
    error: Color(0xFFFFB4AB),
    errorContainer: Color(0xFF93000A),
    onError: Color(0xFF690005),
    onErrorContainer: Color(0xFFFFDAD6),
    background: Color(0xFF001B3D),
    onBackground: Color(0xFFD6E3FF),
    surface: Color(0xFF001B3D),
    onSurface: Color(0xFFD6E3FF),
    surfaceVariant: Color(0xFF44474E),
    onSurfaceVariant: Color(0xFFC4C6D0),
    outline: Color(0xFF8E9099),
    onInverseSurface: Color(0xFF001B3D),
    inverseSurface: Color(0xFFD6E3FF),
    inversePrimary: Color(0xFF2B5DA8),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFFABC7FF),
    outlineVariant: Color(0xFF44474E),
    scrim: Color(0xFFD7E3FF),
  );
}
