---
    name: "release"
    
    on:
      push:
        tags:
          - v*.*.*
      workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'     
            required: true
            default: 'warning'
    
    jobs:
      flutter-build-android:
        name: "Release for android"
        runs-on: "ubuntu-latest" 
        permissions: write-all
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Extract tag name
            run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            shell: bash
          - name: Echo build progress
            run: echo "flutter_template_android_${{ env.tag }}.apk build progress"
            shell: bash
          - name: Install dependencies
            run: |
              sudo apt-get update
              sudo apt-get install -y clang cmake libgtk-3-dev ninja-build libayatana-appindicator3-dev libasound2-dev
            shell: bash
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'          
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
          - name: Get Flutter dependencies
            run: flutter pub get
            shell: bash
          - name: Build Flutter for Android
            run: flutter build apk --split-per-abi
            shell: bash
          - name: Package android build output
            run: cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk flutter_template_android_${env:tag}.apk
            shell: bash

          - name: Upload android outputs
            uses: actions/upload-artifact@v4
            with:
              name: android_outputs
              path: flutter_template_android_*.apk

      flutter-build-windows:
        name: "Release for windows"
        runs-on: "windows-latest"
        permissions: write-all
    
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - run: |
                  $tag = "${{ github.ref }}".Replace('refs/tags/', '')
                  echo "tag=$(echo $tag)" >> $env:GITHUB_ENV
          - run: echo "flutter_template_windows_${env:tag}.zip build progress"
          - run: choco install yq
          - name: Enable Git longpaths
            run: git config --system core.longpaths true
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              channel: stable
              flutter-version-file: pubspec.yaml
              # cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
              # cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
              # pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
              # pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          - name: Set up Java
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '18'
          - run: flutter pub get
          - run: flutter build windows   
          - run: Compress-Archive build/windows/x64/runner/Release/flutter_template_windows_${env:tag}.zip
          - name: Upload windows outputs
            uses: actions/upload-artifact@v4
            with:
              name: windows_outputs
              path: |
                flutter_template_windows_*.zip

      release:
        name: "Release"
        runs-on: "ubuntu-latest"
        needs: [flutter-build-android,flutter-build-windows] 
        permissions: write-all
        steps:
          - name: Clone repository
            uses: actions/checkout@v4

          - name: Extract tag name
            run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            shell: bash

          # - name: Set up JDK 17
          #   uses: actions/setup-java@v3
          #   with:
          #     java-version: '17'
          #     distribution: 'temurin'

          # - name: Setup Android SDK
          #   uses: android-actions/setup-android@v3

          # - name: Setup Android build tools
          #   run: sdkmanager "build-tools;34.0.0"

          
          - name: Download android build file
            uses: actions/download-artifact@v4
            with:
              name: android_outputs
              path: android_outputs 

          - name: List files in android_outputs directory
            run: ls -l android_outputs   

          - name: Copy android build file to unsigned floder
            run: | 
              mkdir build
              mkdir build/unsigned
              cp android_outputs/* build/unsigned/flutter_template_android_${{ env.tag }}.apk

          - name: Download windows build file
            uses: actions/download-artifact@v4
            with:
              name: windows_outputs
              path: windows_outputs  
          - name: List files in windows_outputs directory
            run: ls -l windows_outputs   
          - name: Copy windows build file to root
            run: cp windows_outputs/* flutter_template_windows_${{ env.tag }}.zip


          # - name: Create release
          #   uses: "marvinpinto/action-automatic-releases@latest"
          #   with:
          #     repo_token: "${{ secrets.TOKEN }}"
          #     prerelease: false
          #     # draft: true
          #     files: |
          #       build/unsigned/*.apk

          - name: Create release
            uses: softprops/action-gh-release@v1
            with:
              draft: true
              files: |
                build/unsigned/*.apk
                flutter_template_windows_*.zip
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN }}
